baseURL = "https://redzuurdesem.be"
title = "Red Zuurdesem"
publishDir = "docs"
languageCode = "nl-BE"

googleAnalytics = "UA-117973708-1"

##### 
# theme config
# see https://learn.netlify.com/en/basics/installation/
theme = "hugo-theme-learn"

[Author]
  name = "Wouter Groeneveld"
  email = "wouter.groeneveld@gmail.com"

[params]
themeVariant = "green"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  extensionsmask = ["fencedCode"]
  fractions = false

[[menu.shortcuts]] 
name = "<i class='fa fa-facebook'></i> Facebook"
identifier = "ds"
url = "https://facebook.com/redzuurdesem"
weight = 10

