baseURL = "https://redzuurdesem.be"
title = "Red Zuurdesem"
publishDir = "docs"
languageCode = "nl"
DefaultContentLanguage = "nl"

PaginatePath = "pagina"

ignorefiles = [ "content/boek/src/.*" ]
theme = "desem-swift-theme"

[params]
  logo = "/images/badge.png"
  copyright = "Copyright 2020 Red Zuurdesem"
  description = "Red Zuurdesem: Zuurdesembrood bakken opnieuw populair maken."

[Author]
  name = "Wouter Groeneveld"

# For search functionnality
[outputs]
home = [ "HTML", "RSS" ]

[markup]
  defaultMarkdownHandler = "goldmark"
  
  [markup.goldmark.renderer]
    unsafe= true

  [markup.highlight]
    codeFences = true
    
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
