baseURL = "https://redzuurdesem.be"
title = "Red Zuurdesem"
publishDir = "docs"
languageCode = "nl"
DefaultContentLanguage = "nl"

PaginatePath = "pagina"

ignorefiles = [ "content/boek/src/.*" ]
theme = "desem-swift-theme"

[params]
logo = "/images/badge.png"
fathomid = "BUDSM"

# For search functionnality
[outputs]
home = [ "HTML", "RSS" ]

# https://gohugo.io/getting-started/configuration-markup (ofwel de oude unsafe togglen?) - is nodig, Wordpress export bevat veel HTML!
[markup]
	defaultMarkdownHandler = "blackfriday"

[blackfriday]
  extensionsmask = ["fencedCode"]
  fractions = false

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
